# Generated by Django 5.0.4 on 2024-04-21 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('f1', models.CharField(max_length=255)),
                ('f2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestOneToMany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestManyToOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.testmodel')),
            ],
        ),
        migrations.AddField(
            model_name='testmodel',
            name='my_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.testonetomany'),
        ),
    ]
