# Generated by Django 5.0.4 on 2024-04-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='f1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='f2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
