# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_querysets/lib/query.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1egrpc_querysets/lib/query.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xe9\x02\n\x05Query\x12\x17\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x07.Action\x12\x33\n\rfilter_kwargs\x18\x03 \x01(\x0b\x32\x17.google.protobuf.StructH\x00\x88\x01\x01\x12\x34\n\x0e\x65xclude_kwargs\x18\x04 \x01(\x0b\x32\x17.google.protobuf.StructH\x01\x88\x01\x01\x12\x18\n\x0bstart_index\x18\x05 \x01(\x03H\x02\x88\x01\x01\x12\x16\n\tend_index\x18\x06 \x01(\x03H\x03\x88\x01\x01\x12\r\n\x05order\x18\x07 \x03(\t\x12\x31\n\x0bobject_data\x18\x08 \x01(\x0b\x32\x17.google.protobuf.StructH\x04\x88\x01\x01\x12\x15\n\rresource_type\x18\t \x01(\tB\x10\n\x0e_filter_kwargsB\x11\n\x0f_exclude_kwargsB\x0e\n\x0c_start_indexB\x0c\n\n_end_indexB\x0e\n\x0c_object_data\"J\n\x08Response\x12\x17\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x07.Action\x12%\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct*M\n\x06\x41\x63tion\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06SELECT\x10\x01\x12\n\n\x06\x43REATE\x10\x02\x12\n\n\x06\x44\x45LETE\x10\x03\x12\n\n\x06UPDATE\x10\x04\x12\t\n\x05\x43OUNT\x10\x05\x32\x61\n\x0eRemoteQueryset\x12\"\n\x0bSingleQuery\x12\x06.Query\x1a\t.Response0\x01\x12+\n\x12TransactionalQuery\x12\x06.Query\x1a\t.Response(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_querysets.lib.query_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ACTION']._serialized_start=504
  _globals['_ACTION']._serialized_end=581
  _globals['_QUERY']._serialized_start=65
  _globals['_QUERY']._serialized_end=426
  _globals['_RESPONSE']._serialized_start=428
  _globals['_RESPONSE']._serialized_end=502
  _globals['_REMOTEQUERYSET']._serialized_start=583
  _globals['_REMOTEQUERYSET']._serialized_end=680
# @@protoc_insertion_point(module_scope)
