# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_querysets.lib import query_pb2 as grpc__querysets_dot_lib_dot_query__pb2


class RemoteQuerysetStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SingleQuery = channel.unary_stream(
                '/RemoteQueryset/SingleQuery',
                request_serializer=grpc__querysets_dot_lib_dot_query__pb2.Query.SerializeToString,
                response_deserializer=grpc__querysets_dot_lib_dot_query__pb2.Response.FromString,
                )
        self.TransactionalQuery = channel.stream_stream(
                '/RemoteQueryset/TransactionalQuery',
                request_serializer=grpc__querysets_dot_lib_dot_query__pb2.Query.SerializeToString,
                response_deserializer=grpc__querysets_dot_lib_dot_query__pb2.Response.FromString,
                )


class RemoteQuerysetServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SingleQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransactionalQuery(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteQuerysetServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SingleQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.SingleQuery,
                    request_deserializer=grpc__querysets_dot_lib_dot_query__pb2.Query.FromString,
                    response_serializer=grpc__querysets_dot_lib_dot_query__pb2.Response.SerializeToString,
            ),
            'TransactionalQuery': grpc.stream_stream_rpc_method_handler(
                    servicer.TransactionalQuery,
                    request_deserializer=grpc__querysets_dot_lib_dot_query__pb2.Query.FromString,
                    response_serializer=grpc__querysets_dot_lib_dot_query__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RemoteQueryset', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RemoteQueryset(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SingleQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/RemoteQueryset/SingleQuery',
            grpc__querysets_dot_lib_dot_query__pb2.Query.SerializeToString,
            grpc__querysets_dot_lib_dot_query__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TransactionalQuery(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/RemoteQueryset/TransactionalQuery',
            grpc__querysets_dot_lib_dot_query__pb2.Query.SerializeToString,
            grpc__querysets_dot_lib_dot_query__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
